// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxntyshivhxtixkevulz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4bnR5c2hpdmh4dGl4a2V2dWx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NzM3NTgsImV4cCI6MjA1ODI0OTc1OH0.v2Y3L_iFQbOfJeDRVH6_MXMDWN1VPXnOVwM-attVFz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);